---- Popula a tabela de usuários
INSERT INTO TB_USUARIO (NOME, LOGIN, SENHA) VALUES ('Administrador', 'admin', '1234');
INSERT INTO TB_USUARIO (NOME, LOGIN, SENHA) VALUES ('Usuário Teste', 'usuario', 'abcd');

-- Popula a tabela de tarefas
INSERT INTO TB_TAREFA (TITULO, DESCRICAO, STATUS, USUARIO_ID, DATA_CADASTRO, DATA_ATUALIZACAO)
VALUES ('Tarefa Inicial', 'Descrição da tarefa inicial', 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_TAREFA (TITULO, DESCRICAO, STATUS, USUARIO_ID, DATA_CADASTRO, DATA_ATUALIZACAO)
VALUES ('Segunda Tarefa', 'Outra tarefa de teste', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_TAREFA (TITULO, DESCRICAO, STATUS, USUARIO_ID, DATA_CADASTRO, DATA_ATUALIZACAO)
VALUES ('Tarefa do Usuário', 'Tarefa para outro usuário', 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);