DROP TABLE IF EXISTS TB_TAREFA;
DROP TABLE IF EXISTS TB_USUARIO;

CREATE TABLE IF NOT EXISTS TB_USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(300) NOT NULL,
    LOGIN VARCHAR(300) NOT NULL,
    SENHA VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_TAREFA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(300) NOT NULL,
    DESCRICAO VARCHAR(500),
    STATUS INT NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_ID BIGINT NOT NULL
);
